### ISSUE TITLE
ggplot2 needs to have been explicitly loaded or add_griddap() fails

### ISSUE THREAD

**Issue by rmendels** [ropensci/plotdap#3]
problem occurs in lines 335-336 in the file plotdap.R

        scale_fill_gradientn(name = lazyeval::f_text(var), colors = cols),
        scale_colour_gradientn(colors = cols),

needs to either be  imported or have ggplot2::scale_fill_gradientn  etc.

**Comment by cpsievert** [comment]
Thanks!
