### ISSUE TITLE
Problems due to updates in R (to 3.5.0), ggplot2 (to 3.0.0) and gganimate

### ISSUE THREAD

**Issue by rmendels** [ropensci/plotdap#4]
I am running a system that has the latest R, ggplot2, sf and gganimate.    The combination breaks a lot of things in `plotdap`.  You can reproduce this just by updating your R to the latest, and running all the examples in the README at the front, but correct to get the data from https://coastwatch.pfeg.noaa.gov/erddap/ due to a problem in `rerddap` and the very recent versions of Tomcat  (see - https://github.com/ropensci/rerddap/issues/72)

For example:
```r
murSST <- griddap(
 'jplMURSST41', latitude = c(22, 51), longitude = c(-140, -105),
time = c('last', 'last'), fields = 'analysed_sst', url = 'https://coastwatch.pfeg.noaa.gov/erddap/'
 )
options(digits = 2)
# remove plotting margins
par(mar = c(0, 0, 0, 0))
add_griddap(
 plotdap("base", crs = "+proj=robin"), 
 murSST, ~analysed_sst, maxpixels = 50000
)
```

produces:

![image](https://user-images.githubusercontent.com/1919031/42404099-1cbcdbf4-813b-11e8-8dd1-e549077f2388.png)

while:

```r
add_griddap(
 plotdap(crs = "+proj=robin"), 
 murSST, ~analysed_sst, maxpixels = 50000
)

```

produces:

![image](https://user-images.githubusercontent.com/1919031/42404132-758eeff6-813b-11e8-8e3f-77700abcf13c.png)

the example:

```r
plotdap() %>%
  add_griddap(murSST, ~analysed_sst, maxpixels = 50000) %>%
  add_tabledap(sardines, ~subsample_count)
```

produces the following which while has a correct colorbar,  has washed out the map  (it produces the following warnings, most likely from ggplot2):

![rplot](https://user-images.githubusercontent.com/1919031/42404462-26a39218-813e-11e8-8584-9bbb7a2ad713.png)

and none of the gganimate examples work, for example the sardine code:

```r
add_tabledap(
  plotdap(crs = "+proj=robin"), 
  sardines, 
  ~subsample_count, 
  color = "density", 
  shape = 4, 
  animate = TRUE
)
```
give the error:

Warning: Ignoring unknown aesthetics: frame
Error in get(x, envir = ns, inherits = FALSE) : 
  object 'gganimate' not found.  

gpplot2  (version 3.0.0) now has full support for geom_sf(), and can produce some nice results,  for example:

```r
add_tabledap(
  plotdap(crs = "+proj=robin", mapTitle = "Log subsample count"), 
  sardines, 
  ~log2(subsample_count)
)
```

produces:

![image](https://user-images.githubusercontent.com/1919031/42404511-8968fbcc-813e-11e8-8b31-162cecb54341.png)

which is really nice.

**Comment by sckott** [comment]
@cpsievert do you have time to have a look at this?

**Comment by cpsievert** [comment]
I'm not exactly sure why the first plot doesn't render correctly now, but it's possible that it's related to sf bug(s), and maybe related to https://github.com/r-spatial/sf/issues/793.

For the gganimate problem(s), there's a GitHub release for the old gganimate API which you can install this way. It shouldn't be a huge project to update the new API, but that first issue is more worrisome, so I'll try my best to at least help identify/fix the issue there.

```r
remotes::install_github("thomasp85/gganimate@v0.1.1")
```
